### PR TITLE
fix seq/iseq, incl. persistence

### PR DESCRIPTION
**Pull request by mpollmeier**
depends on https://github.com/ShiftLeftSecurity/overflowdb/pull/204

### CODE REVIEW

**Review by ml86 — APPROVED** [review]

**Comment by bbrehm** [comment]
Can you write some words about the problem this addresses?

So, there is a potential mismatch between JVM types we want to use on the heap, and types we want to use for the overflowdb code.

Why is the converter a virtual function per-node? Isn't it always the same function? Then it could be static. Or if we want to be clever / flexible, then the converter must be per-node-and-per-property.

I think we should just designate one getter-function and one setter-function on nodeDb that is to be used for serialization/deserialization, and that is responsible for everything. This getter/setter is for overflowdb only. Then we internally  document the format and are happy. We could e.g. just use the existing get-dictionary and setter functions -- they have almost no valid use outside of odb code. Longer term we probably want to deprecate (not remove at first, `@deprecate` and see how many warnings we get) most other accessors that are inherited from the abominable tinkergraph-inspired Node interface (basically everything that uses strings to convey what field we're talking about).

Natural format would be: String is String; sequence is Array; primitives are boxed; optionals are either null or a value (`Some(null)` is considered invalid); empty sequences have an alternative valid encoding as `null`.

The array repacking could be done zero-copy via ArraySeq unsafeArray and unsafeWrapArray.

**Comment by mpollmeier** [comment]
Yes it's always the same conversion, we could make it a static function. The only reason I didn't do that is because the NodeSerializer currently only needs a NodeDb handle, nothing else. Yes from there we could lookup the graph and then some registered conversion function, but it felt like this was more complicated (setup and testing wise) and not really faster. 

Regarding that one method that handles everything for persistence: that's essentially already there: `propertiesMapWithoutDefaults`. I was thinking of just using that and renaming it, however then we'd need to handle edge properties separately...

In a way the current proposal is ugly, because `NodeDb.convertPropertyForStorage` is also responsible for converting the properties of it's adjacent edges, so I guess the cleanest option is to go for something static, which is being generated by the codegen and then registered during graph startup. Do you have any thoughts @bbrehm?

**Comment by bbrehm** [comment]
re properties of adjacent edges:
...as far as I know, we have no edge properties? I can't really comment on that, haven't looked into edge properties for a while.

Otherwise, yes: I'd put the conversion into `propertiesMapWithoutDefaults`.

I am totally OK with having an additional separate `convertPropertyForEdge` function, and I'm also completely happy if this is a virtual function -- it is never called anyway, and I try not to look too deeply into hypothetical performance, aesthetics or maintainability of dead code.

**Comment by fabsx00** [comment]
We are using edge properties for the REACHING_DEF edges in the OSS data flow tracker.

**Review by bbrehm — APPROVED** [review]
Ok, then I don't want to block progress here -- we can revisit this later. 

I think we have consensus that this is somewhat of a kludge, but no one has an immediate better idea?

**Comment by mpollmeier** [comment]
superseded by https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/92

**Pull request closed without merging**
