### PR TITLE
mutation and cloning of NewNodes

### PR DESCRIPTION
**Pull request by mpollmeier**
Based on https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/102, but actually more like https://github.com/ShiftLeftSecurity/overflowdb-codegen/issues/101
Alternative to https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/103, which contains a few things that are up to debate. 

Main differences to https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/102:
* copy without implicit and cast, while keeping type inference
* remove additional Builder
* allow both builder and `newNode.member = xyz` setters
* implement Product for nice repl rendering

### CODE REVIEW

**Comment by bbrehm** [comment]
This does not work. Consider
```
      val downcasted: NewNode = original
      val upcasted = downcasted match {
        case node: NewNode with HasNameNew => node
      case _ => null
      }
      upcasted.name = "A"
      val upcastedCopy = upcasted.copy
      upcastedCopy.name = "C"
```
this throws
```
[error] /home/bruhns/repos/overflowdb-codegen/integration-tests/tests/src/test/scala/Schema02Test.scala:41:20: value name is not a member of testschema02.nodes.NewNode
[error]       upcastedCopy.name = "C"
```
In this example, `upcasted` has static type `NewNode with HasNameNew`. When we invoke copy, then we lose the additional type info and end up with static type `NewNode`.

The correct static return type of `copy` invoked on anything known to implement the trait `NewNode` is "the static type of the objec on which `copy` is invoked".

**Comment by mpollmeier** [comment]
thanks! `copy` now works for your upcasted example, `this.type` to the rescue

**Comment by bbrehm** [comment]
I'm fine with https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/104/commits/993cbca117a9a04bebbddf8dd8a24ca9a2a4f84d, but removing the `BaseNodeNew` classes is a problem in https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/104/commits/300807768be80dad55adb500adebee38e5a88875

The entire point of this exercise was to allow simple functions that take in some kind of NewNode, duplicate it, and then mutate it.

This means that we should have a similar type hierarchy for NewNode as for StoredNode.

**Review by bbrehm — APPROVED** [review]
So, I asked the people on scalalang discourse. It appears like this is not really right, as `this.type` apparently means "same instance", not "same type" (if I were to guess, it's because of inner classes that capture their outer classes).

cf https://github.com/scala/docs.scala-lang/pull/2195 and https://users.scala-lang.org/t/guarantees-of-this-type/7822/

I'm ok with merging as is -- I think the fallout from violating official language semantics is manageable in the short term, and I don't want to block anyone by too much pedantry.

Slightly longer term, we probably should go for the JVM clone-intrinsic plus implicit (the switch should be source-code compatible, and we don't attempt bytecode compatibility anyways). That gets rid of the iffy language violation, and it allows people to subclass NewNodes (makes more sense and is way safer than subclassing NodeRef, which is something that people actually do!).

**Pull request merged**
