### PR TITLE
don't hold Options in internal fields any more

### PR DESCRIPTION
**Pull request by mpollmeier**
* this should shave off a lot of memory
* options are still used when the public accessors are used
* refactor CodeGen.generateNewNodeSource: use pattern match
* ISeq: add test, fix and complete implementation
* use Seq basetype rather than (often-) suboptimal List

### CODE REVIEW

**Comment by mpollmeier** [comment]
I'll create a separate PR for edges and contained nodes, trying to keep this PR small-ish.

**Review by fabsx00 — APPROVED** [review]

**Comment by bbrehm** [comment]
codepropertygraph does not compile with this -- is this intended?

```
[error] /home/bruhns/repos2/codepropertygraph/schema/target/odb-codegen/io/shiftleft/codepropertygraph/generated/nodes/Location.scala:244:53: type mismatch;
[error]  found   : io.shiftleft.codepropertygraph.generated.nodes.AbstractNode
[error]  required: Option[io.shiftleft.codepropertygraph.generated.nodes.AbstractNode]
[error]       case "node" => this._node = value.asInstanceOf[AbstractNode]
[error]                                                     ^
[error] one error found
[error] (domainClasses / Compile / compileIncremental) Compilation failed
```

**Comment by bbrehm** [comment]
As a further optimization (some PRs down the line), we should consider storing primitives as primitives with an extra boolean to signify null-ness.

E.g. `lineNumber: Option[Integer]` could be `_lineNumber:Int = 0` and `_hasLineNumber:Boolean = false`, with `def lineNumber: Option[Integer] = if(_hasLineNumber) Some(java.lang.Integer.valueOf(_lineNumber)) else None`.

Same for non-optional primitives:

`order: java.lang.Integer` as `_order:Int = 0` and `_hasOrder:Boolean = false`, with `def order: Integer = if(_hasOrder) java.lang.Integer.valueOf(_order)) else null`.

Without compressed OOPs, this always saves memory (4+1 bytes vs 8 bytes -- alignment structure padding should be a small concern if we have multiple fields, because afaiu the JVM is permitted to reorder fields); with compressed OOPs this often saves memory (depending on how often the boxed Integer is reused by the jvm). Crucially this gets rid of another indirection and potential cache miss.

That other proposed change requires serious benchmarking, though: If the JVM cannot elide the allocation of the java.lang.Integer, then it might be a wash (if the box gets allocated, then reading it is still fast -- either L1 or even store buffer. But this creates GC pressure; furthermore all perf from that optimization are moot if the Int was small enough to be interned and in cache anyway).

**Review by bbrehm — CHANGES_REQUESTED** [review]
Let's get rid of codepropertygraph compile errors before merging

**Comment by mpollmeier** [comment]
Thanks for checking cpg compat, yes quite likely that it needs some adjustments. 
I usually check downstream compat before merging anyway, just didn't have time to do that yesterday and wanted to get this out for review.

**Comment by mpollmeier** [comment]
cpg pr: https://github.com/ShiftLeftSecurity/codepropertygraph/pull/1276

**Comment by mpollmeier** [comment]
whoopsie, forgot that we should first finish that discussion about defaults before merging this.

**Pull request merged**
