### PR TITLE
mutation and cloning of NewNodes

### PR DESCRIPTION
**Pull request by mpollmeier**
Based on https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/102, but actually more like https://github.com/ShiftLeftSecurity/overflowdb-codegen/issues/101
Most importantly, I don't think we need/want TypedCopyable.

### CODE REVIEW

**Review by bbrehm — COMMENTED** [review]
After consideration, I really don't like this: This interface suggests that it is possible to mutate StoredNode, when it is in fact not possible.

I'm ok with the approach to `copy`, though.

**Comment by mpollmeier** [comment]
> This interface suggests that it is possible to mutate StoredNode, when it is in fact not possible.

but but but... `StoredNodes` _are_ mutable, we only didn't have the domain-specific setters yet. So far you would have to invoke the generic setter `Element.setProperty`: https://github.com/ShiftLeftSecurity/overflowdb/blob/master/core/src/main/java/overflowdb/Element.java#L42

**Comment by bbrehm** [comment]
They are not mutable for users. All mutations must go through diffgraph, and the fact that the mutation is accessible to end-users without reflection is a legacy problem inherited from tinkerpop.

**Comment by mpollmeier** [comment]
superseded by https://github.com/ShiftLeftSecurity/overflowdb-codegen/pull/104

**Pull request closed without merging**
