### PR TITLE
CpgNode: rename to AbstractNode

### PR DESCRIPTION
**Pull request by mpollmeier**
there's nothing cpg specific to it, so might as well reflect it in the name

also: upgrade sbt

### CODE REVIEW

**Comment by fabsx00** [comment]
We still have `Node`, `NewNode`, and `StoredNode` as well, right? So, what's the difference between `CpgNode` and `Node`?

**Comment by mpollmeier** [comment]
Hmm, some food for thought...
Yes, we still have `Node`, `NewNode` and `StoredNode`. This is just a rename `CpgNode` -> `AbstractNode`. 

Let's go through them one by one:
* `Node` is actually in the package `overflowdb` and used all over the odb codebase, it was formerlly called `Vertex` in Tinkergraph. And all nodes in ODB are 'stored', so I'd prefer to not call that one `StoredNode`
* `StoredNode` extends `Node` and `AbstractNode` and foremost brings in the edge iterators, e.g. `def _aliasOfIn: java.util.Iterator[StoredNode]`, which Markus and Bernhard fought hard to keep when I tried to remove them. They needed those edge accssors on this abstract level (rather than on the specific node e.g. `Method`). 
* `NewNode` extends `AbstractNode` and is just for DiffGraph
* `AbstractNode` is the parent of `StoredNode` and `NewNode`

If it wasn't for those edge iterators we could drop `StoredNode`, but as it is I guess we need to keep it 

If we named `AbstractNode` just `Node`, we'd either need a new name for `overflowdb.Node` (could go back to `Vertex`...) or fully qualify it when we use it. Given that we rarely use it directly, I'd be ok with the latter - thoughts?

**Comment by fabsx00** [comment]
If I remember correctly, then `StoredNode` is also associated with a graph while `NewNode` is not, so, I'm not sure we could actually drop `StoredNode` if it wasn't for edge iterators. Personally, I'd like to see those edge iterators disappear, but that's a different topic.

So, since renaming `AbstractNode` to `Node` would mean that we still have two types that happen to just have the same name, I actually think keeping it at `AbstractNode` is better as it's slightly less confusing.

**Review by fabsx00 — APPROVED** [review]

**Comment by mpollmeier** [comment]
> If I remember correctly, then StoredNode is also associated with a graph while NewNode is not

Yes exactly. 

> I'm not sure we could actually drop StoredNode if it wasn't for edge iterators.

Yes we could. Example: `generated.nodes.Xyz` would extend `AbstractNode` and `overflowdb.Node` (instead of `generated.nodes.StoredNode`), and `generated.nodes.NewXyz` would extend `AbstractNode`. 
But yes, different topic.

**Pull request merged**
